### ISSUE TITLE
Inserting a pipe for a block parameter (`|`), the cursor is placed after the automatically-added closing pipe

### ISSUE THREAD

**Issue by taylorthurlow** [zed-extensions/ruby#6]
When opening a block with a block parameter:

```ruby
foo do 
#      ^ cursor location
```

Upon inserting the first `|`:

```ruby
foo do ||
#        ^ cursor location
```

I'm using extension version `0.2.2`, and this happens with all language servers disabled. If I recall this started happening in the last few months. I haven't seen this reported in the base zed repo, so I'm not sure what else could make my situation special.

**Comment by vitallium** [comment]
Hi, this is caused by Ruby LSP not the Zed editor itself. There is the `handle_pipe` (`|`) method in the Ruby LSP that does that - https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/requests/on_type_formatting.rb#L85

Here is the same scenario but with disabled Ruby LSP:

```jsonc
  "languages": {
    "Ruby": {
      "language_servers": []
    }
  },
```


https://github.com/user-attachments/assets/1b173d30-835a-4868-94d5-057a97d737b4



Notice, that I initially disabled all LSPs but then I re-enabled the Ruby LSP (and Rubocop) to reproduce this issue.

**Comment by taylorthurlow** [comment]
@vitallium Ah, crap. I must have done something wrong in disabling the language servers... sorry about that. I appreciate the video as well.

**Comment by willcosgrove** [comment]
@vitallium thanks for finding the source of the problem.

It looks like that specific feature of Ruby LSP can be disabled with these Zed settings:

```json
{
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "onTypeFormatting": false
        }
      }
    }
  }
}
```
